import { Inter, Rubik } from "next/font/google";
import "./globals.css";
import Nav from "@/components/common/Nav";

const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
